#pragma once
#include "ingestion/test_fixtures.hpp"
namespace crashcore::fixtures {
inline std::vector<std::vector<std::uint8_t>> fixture_round_451() { RoundSpec s; s.gameId=70451; s.finalMult=1.08; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_452() { RoundSpec s; s.gameId=70452; s.finalMult=1.16; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_453() { RoundSpec s; s.gameId=70453; s.finalMult=1.24; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_454() { RoundSpec s; s.gameId=70454; s.finalMult=1.32; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_455() { RoundSpec s; s.gameId=70455; s.finalMult=1.40; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_456() { RoundSpec s; s.gameId=70456; s.finalMult=1.48; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_457() { RoundSpec s; s.gameId=70457; s.finalMult=1.56; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_458() { RoundSpec s; s.gameId=70458; s.finalMult=1.64; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_459() { RoundSpec s; s.gameId=70459; s.finalMult=1.72; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_460() { RoundSpec s; s.gameId=70460; s.finalMult=1.80; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_461() { RoundSpec s; s.gameId=70461; s.finalMult=1.88; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_462() { RoundSpec s; s.gameId=70462; s.finalMult=1.96; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_463() { RoundSpec s; s.gameId=70463; s.finalMult=2.04; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_464() { RoundSpec s; s.gameId=70464; s.finalMult=2.12; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_465() { RoundSpec s; s.gameId=70465; s.finalMult=2.20; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_466() { RoundSpec s; s.gameId=70466; s.finalMult=2.28; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_467() { RoundSpec s; s.gameId=70467; s.finalMult=2.36; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_468() { RoundSpec s; s.gameId=70468; s.finalMult=2.44; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_469() { RoundSpec s; s.gameId=70469; s.finalMult=2.52; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_470() { RoundSpec s; s.gameId=70470; s.finalMult=2.60; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_471() { RoundSpec s; s.gameId=70471; s.finalMult=2.68; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_472() { RoundSpec s; s.gameId=70472; s.finalMult=2.76; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_473() { RoundSpec s; s.gameId=70473; s.finalMult=2.84; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_474() { RoundSpec s; s.gameId=70474; s.finalMult=2.92; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_475() { RoundSpec s; s.gameId=70475; s.finalMult=3.00; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_476() { RoundSpec s; s.gameId=70476; s.finalMult=3.08; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_477() { RoundSpec s; s.gameId=70477; s.finalMult=3.16; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_478() { RoundSpec s; s.gameId=70478; s.finalMult=3.24; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_479() { RoundSpec s; s.gameId=70479; s.finalMult=3.32; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_480() { RoundSpec s; s.gameId=70480; s.finalMult=3.40; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_481() { RoundSpec s; s.gameId=70481; s.finalMult=3.48; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_482() { RoundSpec s; s.gameId=70482; s.finalMult=3.56; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_483() { RoundSpec s; s.gameId=70483; s.finalMult=3.64; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_484() { RoundSpec s; s.gameId=70484; s.finalMult=3.72; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_485() { RoundSpec s; s.gameId=70485; s.finalMult=3.80; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_486() { RoundSpec s; s.gameId=70486; s.finalMult=3.88; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_487() { RoundSpec s; s.gameId=70487; s.finalMult=3.96; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_488() { RoundSpec s; s.gameId=70488; s.finalMult=4.04; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_489() { RoundSpec s; s.gameId=70489; s.finalMult=4.12; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_490() { RoundSpec s; s.gameId=70490; s.finalMult=4.20; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_491() { RoundSpec s; s.gameId=70491; s.finalMult=4.28; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_492() { RoundSpec s; s.gameId=70492; s.finalMult=4.36; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_493() { RoundSpec s; s.gameId=70493; s.finalMult=4.44; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_494() { RoundSpec s; s.gameId=70494; s.finalMult=4.52; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_495() { RoundSpec s; s.gameId=70495; s.finalMult=4.60; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_496() { RoundSpec s; s.gameId=70496; s.finalMult=4.68; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_497() { RoundSpec s; s.gameId=70497; s.finalMult=4.76; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_498() { RoundSpec s; s.gameId=70498; s.finalMult=4.84; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_499() { RoundSpec s; s.gameId=70499; s.finalMult=4.92; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_500() { RoundSpec s; s.gameId=70500; s.finalMult=5.00; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_501() { RoundSpec s; s.gameId=70501; s.finalMult=5.08; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_502() { RoundSpec s; s.gameId=70502; s.finalMult=5.16; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_503() { RoundSpec s; s.gameId=70503; s.finalMult=5.24; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_504() { RoundSpec s; s.gameId=70504; s.finalMult=5.32; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_505() { RoundSpec s; s.gameId=70505; s.finalMult=5.40; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_506() { RoundSpec s; s.gameId=70506; s.finalMult=5.48; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_507() { RoundSpec s; s.gameId=70507; s.finalMult=5.56; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_508() { RoundSpec s; s.gameId=70508; s.finalMult=5.64; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_509() { RoundSpec s; s.gameId=70509; s.finalMult=5.72; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_510() { RoundSpec s; s.gameId=70510; s.finalMult=5.80; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_511() { RoundSpec s; s.gameId=70511; s.finalMult=5.88; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_512() { RoundSpec s; s.gameId=70512; s.finalMult=5.96; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_513() { RoundSpec s; s.gameId=70513; s.finalMult=6.04; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_514() { RoundSpec s; s.gameId=70514; s.finalMult=6.12; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_515() { RoundSpec s; s.gameId=70515; s.finalMult=6.20; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_516() { RoundSpec s; s.gameId=70516; s.finalMult=6.28; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_517() { RoundSpec s; s.gameId=70517; s.finalMult=6.36; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_518() { RoundSpec s; s.gameId=70518; s.finalMult=6.44; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_519() { RoundSpec s; s.gameId=70519; s.finalMult=6.52; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_520() { RoundSpec s; s.gameId=70520; s.finalMult=6.60; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_521() { RoundSpec s; s.gameId=70521; s.finalMult=6.68; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_522() { RoundSpec s; s.gameId=70522; s.finalMult=6.76; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_523() { RoundSpec s; s.gameId=70523; s.finalMult=6.84; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_524() { RoundSpec s; s.gameId=70524; s.finalMult=6.92; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_525() { RoundSpec s; s.gameId=70525; s.finalMult=7.00; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_526() { RoundSpec s; s.gameId=70526; s.finalMult=7.08; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_527() { RoundSpec s; s.gameId=70527; s.finalMult=7.16; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_528() { RoundSpec s; s.gameId=70528; s.finalMult=7.24; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_529() { RoundSpec s; s.gameId=70529; s.finalMult=7.32; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_530() { RoundSpec s; s.gameId=70530; s.finalMult=7.40; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_531() { RoundSpec s; s.gameId=70531; s.finalMult=7.48; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_532() { RoundSpec s; s.gameId=70532; s.finalMult=7.56; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_533() { RoundSpec s; s.gameId=70533; s.finalMult=7.64; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_534() { RoundSpec s; s.gameId=70534; s.finalMult=7.72; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_535() { RoundSpec s; s.gameId=70535; s.finalMult=7.80; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_536() { RoundSpec s; s.gameId=70536; s.finalMult=7.88; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_537() { RoundSpec s; s.gameId=70537; s.finalMult=7.96; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_538() { RoundSpec s; s.gameId=70538; s.finalMult=8.04; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_539() { RoundSpec s; s.gameId=70539; s.finalMult=8.12; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_540() { RoundSpec s; s.gameId=70540; s.finalMult=1.00; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_541() { RoundSpec s; s.gameId=70541; s.finalMult=1.08; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_542() { RoundSpec s; s.gameId=70542; s.finalMult=1.16; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_543() { RoundSpec s; s.gameId=70543; s.finalMult=1.24; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_544() { RoundSpec s; s.gameId=70544; s.finalMult=1.32; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_545() { RoundSpec s; s.gameId=70545; s.finalMult=1.40; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_546() { RoundSpec s; s.gameId=70546; s.finalMult=1.48; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_547() { RoundSpec s; s.gameId=70547; s.finalMult=1.56; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_548() { RoundSpec s; s.gameId=70548; s.finalMult=1.64; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_549() { RoundSpec s; s.gameId=70549; s.finalMult=1.72; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_550() { RoundSpec s; s.gameId=70550; s.finalMult=1.80; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_551() { RoundSpec s; s.gameId=70551; s.finalMult=1.88; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_552() { RoundSpec s; s.gameId=70552; s.finalMult=1.96; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_553() { RoundSpec s; s.gameId=70553; s.finalMult=2.04; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_554() { RoundSpec s; s.gameId=70554; s.finalMult=2.12; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_555() { RoundSpec s; s.gameId=70555; s.finalMult=2.20; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_556() { RoundSpec s; s.gameId=70556; s.finalMult=2.28; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_557() { RoundSpec s; s.gameId=70557; s.finalMult=2.36; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_558() { RoundSpec s; s.gameId=70558; s.finalMult=2.44; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_559() { RoundSpec s; s.gameId=70559; s.finalMult=2.52; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_560() { RoundSpec s; s.gameId=70560; s.finalMult=2.60; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_561() { RoundSpec s; s.gameId=70561; s.finalMult=2.68; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_562() { RoundSpec s; s.gameId=70562; s.finalMult=2.76; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_563() { RoundSpec s; s.gameId=70563; s.finalMult=2.84; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_564() { RoundSpec s; s.gameId=70564; s.finalMult=2.92; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_565() { RoundSpec s; s.gameId=70565; s.finalMult=3.00; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_566() { RoundSpec s; s.gameId=70566; s.finalMult=3.08; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_567() { RoundSpec s; s.gameId=70567; s.finalMult=3.16; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_568() { RoundSpec s; s.gameId=70568; s.finalMult=3.24; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_569() { RoundSpec s; s.gameId=70569; s.finalMult=3.32; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_570() { RoundSpec s; s.gameId=70570; s.finalMult=3.40; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_571() { RoundSpec s; s.gameId=70571; s.finalMult=3.48; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_572() { RoundSpec s; s.gameId=70572; s.finalMult=3.56; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_573() { RoundSpec s; s.gameId=70573; s.finalMult=3.64; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_574() { RoundSpec s; s.gameId=70574; s.finalMult=3.72; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_575() { RoundSpec s; s.gameId=70575; s.finalMult=3.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_576() { RoundSpec s; s.gameId=70576; s.finalMult=3.88; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_577() { RoundSpec s; s.gameId=70577; s.finalMult=3.96; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_578() { RoundSpec s; s.gameId=70578; s.finalMult=4.04; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_579() { RoundSpec s; s.gameId=70579; s.finalMult=4.12; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_580() { RoundSpec s; s.gameId=70580; s.finalMult=4.20; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_581() { RoundSpec s; s.gameId=70581; s.finalMult=4.28; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_582() { RoundSpec s; s.gameId=70582; s.finalMult=4.36; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_583() { RoundSpec s; s.gameId=70583; s.finalMult=4.44; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_584() { RoundSpec s; s.gameId=70584; s.finalMult=4.52; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_585() { RoundSpec s; s.gameId=70585; s.finalMult=4.60; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_586() { RoundSpec s; s.gameId=70586; s.finalMult=4.68; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_587() { RoundSpec s; s.gameId=70587; s.finalMult=4.76; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_588() { RoundSpec s; s.gameId=70588; s.finalMult=4.84; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_589() { RoundSpec s; s.gameId=70589; s.finalMult=4.92; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_590() { RoundSpec s; s.gameId=70590; s.finalMult=5.00; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_591() { RoundSpec s; s.gameId=70591; s.finalMult=5.08; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_592() { RoundSpec s; s.gameId=70592; s.finalMult=5.16; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_593() { RoundSpec s; s.gameId=70593; s.finalMult=5.24; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_594() { RoundSpec s; s.gameId=70594; s.finalMult=5.32; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_595() { RoundSpec s; s.gameId=70595; s.finalMult=5.40; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_596() { RoundSpec s; s.gameId=70596; s.finalMult=5.48; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_597() { RoundSpec s; s.gameId=70597; s.finalMult=5.56; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_598() { RoundSpec s; s.gameId=70598; s.finalMult=5.64; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_599() { RoundSpec s; s.gameId=70599; s.finalMult=5.72; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_600() { RoundSpec s; s.gameId=70600; s.finalMult=5.80; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_601() { RoundSpec s; s.gameId=70601; s.finalMult=5.88; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_602() { RoundSpec s; s.gameId=70602; s.finalMult=5.96; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_603() { RoundSpec s; s.gameId=70603; s.finalMult=6.04; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_604() { RoundSpec s; s.gameId=70604; s.finalMult=6.12; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_605() { RoundSpec s; s.gameId=70605; s.finalMult=6.20; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_606() { RoundSpec s; s.gameId=70606; s.finalMult=6.28; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_607() { RoundSpec s; s.gameId=70607; s.finalMult=6.36; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_608() { RoundSpec s; s.gameId=70608; s.finalMult=6.44; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_609() { RoundSpec s; s.gameId=70609; s.finalMult=6.52; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_610() { RoundSpec s; s.gameId=70610; s.finalMult=6.60; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_611() { RoundSpec s; s.gameId=70611; s.finalMult=6.68; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_612() { RoundSpec s; s.gameId=70612; s.finalMult=6.76; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_613() { RoundSpec s; s.gameId=70613; s.finalMult=6.84; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_614() { RoundSpec s; s.gameId=70614; s.finalMult=6.92; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_615() { RoundSpec s; s.gameId=70615; s.finalMult=7.00; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_616() { RoundSpec s; s.gameId=70616; s.finalMult=7.08; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_617() { RoundSpec s; s.gameId=70617; s.finalMult=7.16; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_618() { RoundSpec s; s.gameId=70618; s.finalMult=7.24; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_619() { RoundSpec s; s.gameId=70619; s.finalMult=7.32; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_620() { RoundSpec s; s.gameId=70620; s.finalMult=7.40; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_621() { RoundSpec s; s.gameId=70621; s.finalMult=7.48; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_622() { RoundSpec s; s.gameId=70622; s.finalMult=7.56; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_623() { RoundSpec s; s.gameId=70623; s.finalMult=7.64; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_624() { RoundSpec s; s.gameId=70624; s.finalMult=7.72; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_625() { RoundSpec s; s.gameId=70625; s.finalMult=7.80; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_626() { RoundSpec s; s.gameId=70626; s.finalMult=7.88; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_627() { RoundSpec s; s.gameId=70627; s.finalMult=7.96; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_628() { RoundSpec s; s.gameId=70628; s.finalMult=8.04; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_629() { RoundSpec s; s.gameId=70629; s.finalMult=8.12; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_630() { RoundSpec s; s.gameId=70630; s.finalMult=1.00; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_631() { RoundSpec s; s.gameId=70631; s.finalMult=1.08; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_632() { RoundSpec s; s.gameId=70632; s.finalMult=1.16; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_633() { RoundSpec s; s.gameId=70633; s.finalMult=1.24; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_634() { RoundSpec s; s.gameId=70634; s.finalMult=1.32; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_635() { RoundSpec s; s.gameId=70635; s.finalMult=1.40; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_636() { RoundSpec s; s.gameId=70636; s.finalMult=1.48; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_637() { RoundSpec s; s.gameId=70637; s.finalMult=1.56; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_638() { RoundSpec s; s.gameId=70638; s.finalMult=1.64; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_639() { RoundSpec s; s.gameId=70639; s.finalMult=1.72; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_640() { RoundSpec s; s.gameId=70640; s.finalMult=1.80; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_641() { RoundSpec s; s.gameId=70641; s.finalMult=1.88; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_642() { RoundSpec s; s.gameId=70642; s.finalMult=1.96; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_643() { RoundSpec s; s.gameId=70643; s.finalMult=2.04; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_644() { RoundSpec s; s.gameId=70644; s.finalMult=2.12; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_645() { RoundSpec s; s.gameId=70645; s.finalMult=2.20; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_646() { RoundSpec s; s.gameId=70646; s.finalMult=2.28; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_647() { RoundSpec s; s.gameId=70647; s.finalMult=2.36; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_648() { RoundSpec s; s.gameId=70648; s.finalMult=2.44; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_649() { RoundSpec s; s.gameId=70649; s.finalMult=2.52; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_650() { RoundSpec s; s.gameId=70650; s.finalMult=2.60; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_651() { RoundSpec s; s.gameId=70651; s.finalMult=2.68; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_652() { RoundSpec s; s.gameId=70652; s.finalMult=2.76; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_653() { RoundSpec s; s.gameId=70653; s.finalMult=2.84; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_654() { RoundSpec s; s.gameId=70654; s.finalMult=2.92; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_655() { RoundSpec s; s.gameId=70655; s.finalMult=3.00; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_656() { RoundSpec s; s.gameId=70656; s.finalMult=3.08; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_657() { RoundSpec s; s.gameId=70657; s.finalMult=3.16; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_658() { RoundSpec s; s.gameId=70658; s.finalMult=3.24; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_659() { RoundSpec s; s.gameId=70659; s.finalMult=3.32; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_660() { RoundSpec s; s.gameId=70660; s.finalMult=3.40; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_661() { RoundSpec s; s.gameId=70661; s.finalMult=3.48; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_662() { RoundSpec s; s.gameId=70662; s.finalMult=3.56; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_663() { RoundSpec s; s.gameId=70663; s.finalMult=3.64; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_664() { RoundSpec s; s.gameId=70664; s.finalMult=3.72; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_665() { RoundSpec s; s.gameId=70665; s.finalMult=3.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_666() { RoundSpec s; s.gameId=70666; s.finalMult=3.88; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_667() { RoundSpec s; s.gameId=70667; s.finalMult=3.96; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_668() { RoundSpec s; s.gameId=70668; s.finalMult=4.04; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_669() { RoundSpec s; s.gameId=70669; s.finalMult=4.12; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_670() { RoundSpec s; s.gameId=70670; s.finalMult=4.20; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_671() { RoundSpec s; s.gameId=70671; s.finalMult=4.28; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_672() { RoundSpec s; s.gameId=70672; s.finalMult=4.36; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_673() { RoundSpec s; s.gameId=70673; s.finalMult=4.44; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_674() { RoundSpec s; s.gameId=70674; s.finalMult=4.52; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_675() { RoundSpec s; s.gameId=70675; s.finalMult=4.60; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_676() { RoundSpec s; s.gameId=70676; s.finalMult=4.68; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_677() { RoundSpec s; s.gameId=70677; s.finalMult=4.76; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_678() { RoundSpec s; s.gameId=70678; s.finalMult=4.84; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_679() { RoundSpec s; s.gameId=70679; s.finalMult=4.92; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_680() { RoundSpec s; s.gameId=70680; s.finalMult=5.00; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_681() { RoundSpec s; s.gameId=70681; s.finalMult=5.08; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_682() { RoundSpec s; s.gameId=70682; s.finalMult=5.16; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_683() { RoundSpec s; s.gameId=70683; s.finalMult=5.24; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_684() { RoundSpec s; s.gameId=70684; s.finalMult=5.32; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_685() { RoundSpec s; s.gameId=70685; s.finalMult=5.40; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_686() { RoundSpec s; s.gameId=70686; s.finalMult=5.48; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_687() { RoundSpec s; s.gameId=70687; s.finalMult=5.56; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_688() { RoundSpec s; s.gameId=70688; s.finalMult=5.64; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_689() { RoundSpec s; s.gameId=70689; s.finalMult=5.72; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_690() { RoundSpec s; s.gameId=70690; s.finalMult=5.80; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_691() { RoundSpec s; s.gameId=70691; s.finalMult=5.88; s.progressTicks=12; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_692() { RoundSpec s; s.gameId=70692; s.finalMult=5.96; s.progressTicks=13; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_693() { RoundSpec s; s.gameId=70693; s.finalMult=6.04; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_694() { RoundSpec s; s.gameId=70694; s.finalMult=6.12; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_695() { RoundSpec s; s.gameId=70695; s.finalMult=6.20; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_696() { RoundSpec s; s.gameId=70696; s.finalMult=6.28; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_697() { RoundSpec s; s.gameId=70697; s.finalMult=6.36; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_698() { RoundSpec s; s.gameId=70698; s.finalMult=6.44; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_699() { RoundSpec s; s.gameId=70699; s.finalMult=6.52; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_700() { RoundSpec s; s.gameId=70700; s.finalMult=6.60; s.progressTicks=10; return makeRound(s); }
inline int countFixturesExt3() { return 250; }
}
