#pragma once
#include "ingestion/test_fixtures.hpp"
namespace crashcore::fixtures {
inline std::vector<std::vector<std::uint8_t>> fixture_round_201() { RoundSpec s; s.gameId=50201; s.finalMult=7.71; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_202() { RoundSpec s; s.gameId=50202; s.finalMult=7.82; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_203() { RoundSpec s; s.gameId=50203; s.finalMult=7.93; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_204() { RoundSpec s; s.gameId=50204; s.finalMult=8.04; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_205() { RoundSpec s; s.gameId=50205; s.finalMult=8.15; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_206() { RoundSpec s; s.gameId=50206; s.finalMult=8.26; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_207() { RoundSpec s; s.gameId=50207; s.finalMult=8.37; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_208() { RoundSpec s; s.gameId=50208; s.finalMult=8.48; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_209() { RoundSpec s; s.gameId=50209; s.finalMult=8.59; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_210() { RoundSpec s; s.gameId=50210; s.finalMult=1.00; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_211() { RoundSpec s; s.gameId=50211; s.finalMult=1.11; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_212() { RoundSpec s; s.gameId=50212; s.finalMult=1.22; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_213() { RoundSpec s; s.gameId=50213; s.finalMult=1.33; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_214() { RoundSpec s; s.gameId=50214; s.finalMult=1.44; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_215() { RoundSpec s; s.gameId=50215; s.finalMult=1.55; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_216() { RoundSpec s; s.gameId=50216; s.finalMult=1.66; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_217() { RoundSpec s; s.gameId=50217; s.finalMult=1.77; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_218() { RoundSpec s; s.gameId=50218; s.finalMult=1.88; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_219() { RoundSpec s; s.gameId=50219; s.finalMult=1.99; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_220() { RoundSpec s; s.gameId=50220; s.finalMult=2.10; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_221() { RoundSpec s; s.gameId=50221; s.finalMult=2.21; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_222() { RoundSpec s; s.gameId=50222; s.finalMult=2.32; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_223() { RoundSpec s; s.gameId=50223; s.finalMult=2.43; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_224() { RoundSpec s; s.gameId=50224; s.finalMult=2.54; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_225() { RoundSpec s; s.gameId=50225; s.finalMult=2.65; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_226() { RoundSpec s; s.gameId=50226; s.finalMult=2.76; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_227() { RoundSpec s; s.gameId=50227; s.finalMult=2.87; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_228() { RoundSpec s; s.gameId=50228; s.finalMult=2.98; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_229() { RoundSpec s; s.gameId=50229; s.finalMult=3.09; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_230() { RoundSpec s; s.gameId=50230; s.finalMult=3.20; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_231() { RoundSpec s; s.gameId=50231; s.finalMult=3.31; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_232() { RoundSpec s; s.gameId=50232; s.finalMult=3.42; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_233() { RoundSpec s; s.gameId=50233; s.finalMult=3.53; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_234() { RoundSpec s; s.gameId=50234; s.finalMult=3.64; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_235() { RoundSpec s; s.gameId=50235; s.finalMult=3.75; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_236() { RoundSpec s; s.gameId=50236; s.finalMult=3.86; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_237() { RoundSpec s; s.gameId=50237; s.finalMult=3.97; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_238() { RoundSpec s; s.gameId=50238; s.finalMult=4.08; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_239() { RoundSpec s; s.gameId=50239; s.finalMult=4.19; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_240() { RoundSpec s; s.gameId=50240; s.finalMult=4.30; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_241() { RoundSpec s; s.gameId=50241; s.finalMult=4.41; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_242() { RoundSpec s; s.gameId=50242; s.finalMult=4.52; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_243() { RoundSpec s; s.gameId=50243; s.finalMult=4.63; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_244() { RoundSpec s; s.gameId=50244; s.finalMult=4.74; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_245() { RoundSpec s; s.gameId=50245; s.finalMult=4.85; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_246() { RoundSpec s; s.gameId=50246; s.finalMult=4.96; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_247() { RoundSpec s; s.gameId=50247; s.finalMult=5.07; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_248() { RoundSpec s; s.gameId=50248; s.finalMult=5.18; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_249() { RoundSpec s; s.gameId=50249; s.finalMult=5.29; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_250() { RoundSpec s; s.gameId=50250; s.finalMult=5.40; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_251() { RoundSpec s; s.gameId=50251; s.finalMult=5.51; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_252() { RoundSpec s; s.gameId=50252; s.finalMult=5.62; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_253() { RoundSpec s; s.gameId=50253; s.finalMult=5.73; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_254() { RoundSpec s; s.gameId=50254; s.finalMult=5.84; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_255() { RoundSpec s; s.gameId=50255; s.finalMult=5.95; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_256() { RoundSpec s; s.gameId=50256; s.finalMult=6.06; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_257() { RoundSpec s; s.gameId=50257; s.finalMult=6.17; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_258() { RoundSpec s; s.gameId=50258; s.finalMult=6.28; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_259() { RoundSpec s; s.gameId=50259; s.finalMult=6.39; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_260() { RoundSpec s; s.gameId=50260; s.finalMult=6.50; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_261() { RoundSpec s; s.gameId=50261; s.finalMult=6.61; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_262() { RoundSpec s; s.gameId=50262; s.finalMult=6.72; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_263() { RoundSpec s; s.gameId=50263; s.finalMult=6.83; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_264() { RoundSpec s; s.gameId=50264; s.finalMult=6.94; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_265() { RoundSpec s; s.gameId=50265; s.finalMult=7.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_266() { RoundSpec s; s.gameId=50266; s.finalMult=7.16; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_267() { RoundSpec s; s.gameId=50267; s.finalMult=7.27; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_268() { RoundSpec s; s.gameId=50268; s.finalMult=7.38; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_269() { RoundSpec s; s.gameId=50269; s.finalMult=7.49; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_270() { RoundSpec s; s.gameId=50270; s.finalMult=7.60; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_271() { RoundSpec s; s.gameId=50271; s.finalMult=7.71; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_272() { RoundSpec s; s.gameId=50272; s.finalMult=7.82; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_273() { RoundSpec s; s.gameId=50273; s.finalMult=7.93; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_274() { RoundSpec s; s.gameId=50274; s.finalMult=8.04; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_275() { RoundSpec s; s.gameId=50275; s.finalMult=8.15; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_276() { RoundSpec s; s.gameId=50276; s.finalMult=8.26; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_277() { RoundSpec s; s.gameId=50277; s.finalMult=8.37; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_278() { RoundSpec s; s.gameId=50278; s.finalMult=8.48; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_279() { RoundSpec s; s.gameId=50279; s.finalMult=8.59; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_280() { RoundSpec s; s.gameId=50280; s.finalMult=1.00; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_281() { RoundSpec s; s.gameId=50281; s.finalMult=1.11; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_282() { RoundSpec s; s.gameId=50282; s.finalMult=1.22; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_283() { RoundSpec s; s.gameId=50283; s.finalMult=1.33; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_284() { RoundSpec s; s.gameId=50284; s.finalMult=1.44; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_285() { RoundSpec s; s.gameId=50285; s.finalMult=1.55; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_286() { RoundSpec s; s.gameId=50286; s.finalMult=1.66; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_287() { RoundSpec s; s.gameId=50287; s.finalMult=1.77; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_288() { RoundSpec s; s.gameId=50288; s.finalMult=1.88; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_289() { RoundSpec s; s.gameId=50289; s.finalMult=1.99; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_290() { RoundSpec s; s.gameId=50290; s.finalMult=2.10; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_291() { RoundSpec s; s.gameId=50291; s.finalMult=2.21; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_292() { RoundSpec s; s.gameId=50292; s.finalMult=2.32; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_293() { RoundSpec s; s.gameId=50293; s.finalMult=2.43; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_294() { RoundSpec s; s.gameId=50294; s.finalMult=2.54; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_295() { RoundSpec s; s.gameId=50295; s.finalMult=2.65; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_296() { RoundSpec s; s.gameId=50296; s.finalMult=2.76; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_297() { RoundSpec s; s.gameId=50297; s.finalMult=2.87; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_298() { RoundSpec s; s.gameId=50298; s.finalMult=2.98; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_299() { RoundSpec s; s.gameId=50299; s.finalMult=3.09; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_300() { RoundSpec s; s.gameId=50300; s.finalMult=3.20; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_301() { RoundSpec s; s.gameId=50301; s.finalMult=3.31; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_302() { RoundSpec s; s.gameId=50302; s.finalMult=3.42; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_303() { RoundSpec s; s.gameId=50303; s.finalMult=3.53; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_304() { RoundSpec s; s.gameId=50304; s.finalMult=3.64; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_305() { RoundSpec s; s.gameId=50305; s.finalMult=3.75; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_306() { RoundSpec s; s.gameId=50306; s.finalMult=3.86; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_307() { RoundSpec s; s.gameId=50307; s.finalMult=3.97; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_308() { RoundSpec s; s.gameId=50308; s.finalMult=4.08; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_309() { RoundSpec s; s.gameId=50309; s.finalMult=4.19; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_310() { RoundSpec s; s.gameId=50310; s.finalMult=4.30; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_311() { RoundSpec s; s.gameId=50311; s.finalMult=4.41; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_312() { RoundSpec s; s.gameId=50312; s.finalMult=4.52; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_313() { RoundSpec s; s.gameId=50313; s.finalMult=4.63; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_314() { RoundSpec s; s.gameId=50314; s.finalMult=4.74; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_315() { RoundSpec s; s.gameId=50315; s.finalMult=4.85; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_316() { RoundSpec s; s.gameId=50316; s.finalMult=4.96; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_317() { RoundSpec s; s.gameId=50317; s.finalMult=5.07; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_318() { RoundSpec s; s.gameId=50318; s.finalMult=5.18; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_319() { RoundSpec s; s.gameId=50319; s.finalMult=5.29; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_320() { RoundSpec s; s.gameId=50320; s.finalMult=5.40; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_321() { RoundSpec s; s.gameId=50321; s.finalMult=5.51; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_322() { RoundSpec s; s.gameId=50322; s.finalMult=5.62; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_323() { RoundSpec s; s.gameId=50323; s.finalMult=5.73; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_324() { RoundSpec s; s.gameId=50324; s.finalMult=5.84; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_325() { RoundSpec s; s.gameId=50325; s.finalMult=5.95; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_326() { RoundSpec s; s.gameId=50326; s.finalMult=6.06; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_327() { RoundSpec s; s.gameId=50327; s.finalMult=6.17; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_328() { RoundSpec s; s.gameId=50328; s.finalMult=6.28; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_329() { RoundSpec s; s.gameId=50329; s.finalMult=6.39; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_330() { RoundSpec s; s.gameId=50330; s.finalMult=6.50; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_331() { RoundSpec s; s.gameId=50331; s.finalMult=6.61; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_332() { RoundSpec s; s.gameId=50332; s.finalMult=6.72; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_333() { RoundSpec s; s.gameId=50333; s.finalMult=6.83; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_334() { RoundSpec s; s.gameId=50334; s.finalMult=6.94; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_335() { RoundSpec s; s.gameId=50335; s.finalMult=7.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_336() { RoundSpec s; s.gameId=50336; s.finalMult=7.16; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_337() { RoundSpec s; s.gameId=50337; s.finalMult=7.27; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_338() { RoundSpec s; s.gameId=50338; s.finalMult=7.38; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_339() { RoundSpec s; s.gameId=50339; s.finalMult=7.49; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_340() { RoundSpec s; s.gameId=50340; s.finalMult=7.60; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_341() { RoundSpec s; s.gameId=50341; s.finalMult=7.71; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_342() { RoundSpec s; s.gameId=50342; s.finalMult=7.82; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_343() { RoundSpec s; s.gameId=50343; s.finalMult=7.93; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_344() { RoundSpec s; s.gameId=50344; s.finalMult=8.04; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_345() { RoundSpec s; s.gameId=50345; s.finalMult=8.15; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_346() { RoundSpec s; s.gameId=50346; s.finalMult=8.26; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_347() { RoundSpec s; s.gameId=50347; s.finalMult=8.37; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_348() { RoundSpec s; s.gameId=50348; s.finalMult=8.48; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_349() { RoundSpec s; s.gameId=50349; s.finalMult=8.59; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_350() { RoundSpec s; s.gameId=50350; s.finalMult=1.00; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_351() { RoundSpec s; s.gameId=50351; s.finalMult=1.11; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_352() { RoundSpec s; s.gameId=50352; s.finalMult=1.22; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_353() { RoundSpec s; s.gameId=50353; s.finalMult=1.33; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_354() { RoundSpec s; s.gameId=50354; s.finalMult=1.44; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_355() { RoundSpec s; s.gameId=50355; s.finalMult=1.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_356() { RoundSpec s; s.gameId=50356; s.finalMult=1.66; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_357() { RoundSpec s; s.gameId=50357; s.finalMult=1.77; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_358() { RoundSpec s; s.gameId=50358; s.finalMult=1.88; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_359() { RoundSpec s; s.gameId=50359; s.finalMult=1.99; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_360() { RoundSpec s; s.gameId=50360; s.finalMult=2.10; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_361() { RoundSpec s; s.gameId=50361; s.finalMult=2.21; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_362() { RoundSpec s; s.gameId=50362; s.finalMult=2.32; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_363() { RoundSpec s; s.gameId=50363; s.finalMult=2.43; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_364() { RoundSpec s; s.gameId=50364; s.finalMult=2.54; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_365() { RoundSpec s; s.gameId=50365; s.finalMult=2.65; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_366() { RoundSpec s; s.gameId=50366; s.finalMult=2.76; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_367() { RoundSpec s; s.gameId=50367; s.finalMult=2.87; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_368() { RoundSpec s; s.gameId=50368; s.finalMult=2.98; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_369() { RoundSpec s; s.gameId=50369; s.finalMult=3.09; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_370() { RoundSpec s; s.gameId=50370; s.finalMult=3.20; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_371() { RoundSpec s; s.gameId=50371; s.finalMult=3.31; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_372() { RoundSpec s; s.gameId=50372; s.finalMult=3.42; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_373() { RoundSpec s; s.gameId=50373; s.finalMult=3.53; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_374() { RoundSpec s; s.gameId=50374; s.finalMult=3.64; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_375() { RoundSpec s; s.gameId=50375; s.finalMult=3.75; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_376() { RoundSpec s; s.gameId=50376; s.finalMult=3.86; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_377() { RoundSpec s; s.gameId=50377; s.finalMult=3.97; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_378() { RoundSpec s; s.gameId=50378; s.finalMult=4.08; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_379() { RoundSpec s; s.gameId=50379; s.finalMult=4.19; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_380() { RoundSpec s; s.gameId=50380; s.finalMult=4.30; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_381() { RoundSpec s; s.gameId=50381; s.finalMult=4.41; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_382() { RoundSpec s; s.gameId=50382; s.finalMult=4.52; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_383() { RoundSpec s; s.gameId=50383; s.finalMult=4.63; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_384() { RoundSpec s; s.gameId=50384; s.finalMult=4.74; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_385() { RoundSpec s; s.gameId=50385; s.finalMult=4.85; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_386() { RoundSpec s; s.gameId=50386; s.finalMult=4.96; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_387() { RoundSpec s; s.gameId=50387; s.finalMult=5.07; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_388() { RoundSpec s; s.gameId=50388; s.finalMult=5.18; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_389() { RoundSpec s; s.gameId=50389; s.finalMult=5.29; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_390() { RoundSpec s; s.gameId=50390; s.finalMult=5.40; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_391() { RoundSpec s; s.gameId=50391; s.finalMult=5.51; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_392() { RoundSpec s; s.gameId=50392; s.finalMult=5.62; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_393() { RoundSpec s; s.gameId=50393; s.finalMult=5.73; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_394() { RoundSpec s; s.gameId=50394; s.finalMult=5.84; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_395() { RoundSpec s; s.gameId=50395; s.finalMult=5.95; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_396() { RoundSpec s; s.gameId=50396; s.finalMult=6.06; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_397() { RoundSpec s; s.gameId=50397; s.finalMult=6.17; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_398() { RoundSpec s; s.gameId=50398; s.finalMult=6.28; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_399() { RoundSpec s; s.gameId=50399; s.finalMult=6.39; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_400() { RoundSpec s; s.gameId=50400; s.finalMult=6.50; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_401() { RoundSpec s; s.gameId=50401; s.finalMult=6.61; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_402() { RoundSpec s; s.gameId=50402; s.finalMult=6.72; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_403() { RoundSpec s; s.gameId=50403; s.finalMult=6.83; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_404() { RoundSpec s; s.gameId=50404; s.finalMult=6.94; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_405() { RoundSpec s; s.gameId=50405; s.finalMult=7.05; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_406() { RoundSpec s; s.gameId=50406; s.finalMult=7.16; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_407() { RoundSpec s; s.gameId=50407; s.finalMult=7.27; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_408() { RoundSpec s; s.gameId=50408; s.finalMult=7.38; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_409() { RoundSpec s; s.gameId=50409; s.finalMult=7.49; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_410() { RoundSpec s; s.gameId=50410; s.finalMult=7.60; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_411() { RoundSpec s; s.gameId=50411; s.finalMult=7.71; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_412() { RoundSpec s; s.gameId=50412; s.finalMult=7.82; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_413() { RoundSpec s; s.gameId=50413; s.finalMult=7.93; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_414() { RoundSpec s; s.gameId=50414; s.finalMult=8.04; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_415() { RoundSpec s; s.gameId=50415; s.finalMult=8.15; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_416() { RoundSpec s; s.gameId=50416; s.finalMult=8.26; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_417() { RoundSpec s; s.gameId=50417; s.finalMult=8.37; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_418() { RoundSpec s; s.gameId=50418; s.finalMult=8.48; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_419() { RoundSpec s; s.gameId=50419; s.finalMult=8.59; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_420() { RoundSpec s; s.gameId=50420; s.finalMult=1.00; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_421() { RoundSpec s; s.gameId=50421; s.finalMult=1.11; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_422() { RoundSpec s; s.gameId=50422; s.finalMult=1.22; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_423() { RoundSpec s; s.gameId=50423; s.finalMult=1.33; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_424() { RoundSpec s; s.gameId=50424; s.finalMult=1.44; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_425() { RoundSpec s; s.gameId=50425; s.finalMult=1.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_426() { RoundSpec s; s.gameId=50426; s.finalMult=1.66; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_427() { RoundSpec s; s.gameId=50427; s.finalMult=1.77; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_428() { RoundSpec s; s.gameId=50428; s.finalMult=1.88; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_429() { RoundSpec s; s.gameId=50429; s.finalMult=1.99; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_430() { RoundSpec s; s.gameId=50430; s.finalMult=2.10; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_431() { RoundSpec s; s.gameId=50431; s.finalMult=2.21; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_432() { RoundSpec s; s.gameId=50432; s.finalMult=2.32; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_433() { RoundSpec s; s.gameId=50433; s.finalMult=2.43; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_434() { RoundSpec s; s.gameId=50434; s.finalMult=2.54; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_435() { RoundSpec s; s.gameId=50435; s.finalMult=2.65; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_436() { RoundSpec s; s.gameId=50436; s.finalMult=2.76; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_437() { RoundSpec s; s.gameId=50437; s.finalMult=2.87; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_438() { RoundSpec s; s.gameId=50438; s.finalMult=2.98; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_439() { RoundSpec s; s.gameId=50439; s.finalMult=3.09; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_440() { RoundSpec s; s.gameId=50440; s.finalMult=3.20; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_441() { RoundSpec s; s.gameId=50441; s.finalMult=3.31; s.progressTicks=3; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_442() { RoundSpec s; s.gameId=50442; s.finalMult=3.42; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_443() { RoundSpec s; s.gameId=50443; s.finalMult=3.53; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_444() { RoundSpec s; s.gameId=50444; s.finalMult=3.64; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_445() { RoundSpec s; s.gameId=50445; s.finalMult=3.75; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_446() { RoundSpec s; s.gameId=50446; s.finalMult=3.86; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_447() { RoundSpec s; s.gameId=50447; s.finalMult=3.97; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_448() { RoundSpec s; s.gameId=50448; s.finalMult=4.08; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_449() { RoundSpec s; s.gameId=50449; s.finalMult=4.19; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_450() { RoundSpec s; s.gameId=50450; s.finalMult=4.30; s.progressTicks=3; return makeRound(s); }
inline int countFixturesExt2() { return 250; }
}
