#pragma once
#include "ingestion/test_fixtures.hpp"
namespace crashcore::fixtures {
inline std::vector<std::vector<std::uint8_t>> fixture_round_701() { RoundSpec s; s.gameId=90701; s.finalMult=7.06; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_702() { RoundSpec s; s.gameId=90702; s.finalMult=7.12; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_703() { RoundSpec s; s.gameId=90703; s.finalMult=7.18; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_704() { RoundSpec s; s.gameId=90704; s.finalMult=7.24; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_705() { RoundSpec s; s.gameId=90705; s.finalMult=7.30; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_706() { RoundSpec s; s.gameId=90706; s.finalMult=7.36; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_707() { RoundSpec s; s.gameId=90707; s.finalMult=7.42; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_708() { RoundSpec s; s.gameId=90708; s.finalMult=7.48; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_709() { RoundSpec s; s.gameId=90709; s.finalMult=7.54; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_710() { RoundSpec s; s.gameId=90710; s.finalMult=7.60; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_711() { RoundSpec s; s.gameId=90711; s.finalMult=7.66; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_712() { RoundSpec s; s.gameId=90712; s.finalMult=7.72; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_713() { RoundSpec s; s.gameId=90713; s.finalMult=7.78; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_714() { RoundSpec s; s.gameId=90714; s.finalMult=7.84; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_715() { RoundSpec s; s.gameId=90715; s.finalMult=7.90; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_716() { RoundSpec s; s.gameId=90716; s.finalMult=7.96; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_717() { RoundSpec s; s.gameId=90717; s.finalMult=8.02; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_718() { RoundSpec s; s.gameId=90718; s.finalMult=8.08; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_719() { RoundSpec s; s.gameId=90719; s.finalMult=8.14; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_720() { RoundSpec s; s.gameId=90720; s.finalMult=1.00; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_721() { RoundSpec s; s.gameId=90721; s.finalMult=1.06; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_722() { RoundSpec s; s.gameId=90722; s.finalMult=1.12; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_723() { RoundSpec s; s.gameId=90723; s.finalMult=1.18; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_724() { RoundSpec s; s.gameId=90724; s.finalMult=1.24; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_725() { RoundSpec s; s.gameId=90725; s.finalMult=1.30; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_726() { RoundSpec s; s.gameId=90726; s.finalMult=1.36; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_727() { RoundSpec s; s.gameId=90727; s.finalMult=1.42; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_728() { RoundSpec s; s.gameId=90728; s.finalMult=1.48; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_729() { RoundSpec s; s.gameId=90729; s.finalMult=1.54; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_730() { RoundSpec s; s.gameId=90730; s.finalMult=1.60; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_731() { RoundSpec s; s.gameId=90731; s.finalMult=1.66; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_732() { RoundSpec s; s.gameId=90732; s.finalMult=1.72; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_733() { RoundSpec s; s.gameId=90733; s.finalMult=1.78; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_734() { RoundSpec s; s.gameId=90734; s.finalMult=1.84; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_735() { RoundSpec s; s.gameId=90735; s.finalMult=1.90; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_736() { RoundSpec s; s.gameId=90736; s.finalMult=1.96; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_737() { RoundSpec s; s.gameId=90737; s.finalMult=2.02; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_738() { RoundSpec s; s.gameId=90738; s.finalMult=2.08; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_739() { RoundSpec s; s.gameId=90739; s.finalMult=2.14; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_740() { RoundSpec s; s.gameId=90740; s.finalMult=2.20; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_741() { RoundSpec s; s.gameId=90741; s.finalMult=2.26; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_742() { RoundSpec s; s.gameId=90742; s.finalMult=2.32; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_743() { RoundSpec s; s.gameId=90743; s.finalMult=2.38; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_744() { RoundSpec s; s.gameId=90744; s.finalMult=2.44; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_745() { RoundSpec s; s.gameId=90745; s.finalMult=2.50; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_746() { RoundSpec s; s.gameId=90746; s.finalMult=2.56; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_747() { RoundSpec s; s.gameId=90747; s.finalMult=2.62; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_748() { RoundSpec s; s.gameId=90748; s.finalMult=2.68; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_749() { RoundSpec s; s.gameId=90749; s.finalMult=2.74; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_750() { RoundSpec s; s.gameId=90750; s.finalMult=2.80; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_751() { RoundSpec s; s.gameId=90751; s.finalMult=2.86; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_752() { RoundSpec s; s.gameId=90752; s.finalMult=2.92; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_753() { RoundSpec s; s.gameId=90753; s.finalMult=2.98; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_754() { RoundSpec s; s.gameId=90754; s.finalMult=3.04; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_755() { RoundSpec s; s.gameId=90755; s.finalMult=3.10; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_756() { RoundSpec s; s.gameId=90756; s.finalMult=3.16; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_757() { RoundSpec s; s.gameId=90757; s.finalMult=3.22; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_758() { RoundSpec s; s.gameId=90758; s.finalMult=3.28; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_759() { RoundSpec s; s.gameId=90759; s.finalMult=3.34; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_760() { RoundSpec s; s.gameId=90760; s.finalMult=3.40; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_761() { RoundSpec s; s.gameId=90761; s.finalMult=3.46; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_762() { RoundSpec s; s.gameId=90762; s.finalMult=3.52; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_763() { RoundSpec s; s.gameId=90763; s.finalMult=3.58; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_764() { RoundSpec s; s.gameId=90764; s.finalMult=3.64; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_765() { RoundSpec s; s.gameId=90765; s.finalMult=3.70; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_766() { RoundSpec s; s.gameId=90766; s.finalMult=3.76; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_767() { RoundSpec s; s.gameId=90767; s.finalMult=3.82; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_768() { RoundSpec s; s.gameId=90768; s.finalMult=3.88; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_769() { RoundSpec s; s.gameId=90769; s.finalMult=3.94; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_770() { RoundSpec s; s.gameId=90770; s.finalMult=4.00; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_771() { RoundSpec s; s.gameId=90771; s.finalMult=4.06; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_772() { RoundSpec s; s.gameId=90772; s.finalMult=4.12; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_773() { RoundSpec s; s.gameId=90773; s.finalMult=4.18; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_774() { RoundSpec s; s.gameId=90774; s.finalMult=4.24; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_775() { RoundSpec s; s.gameId=90775; s.finalMult=4.30; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_776() { RoundSpec s; s.gameId=90776; s.finalMult=4.36; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_777() { RoundSpec s; s.gameId=90777; s.finalMult=4.42; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_778() { RoundSpec s; s.gameId=90778; s.finalMult=4.48; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_779() { RoundSpec s; s.gameId=90779; s.finalMult=4.54; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_780() { RoundSpec s; s.gameId=90780; s.finalMult=4.60; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_781() { RoundSpec s; s.gameId=90781; s.finalMult=4.66; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_782() { RoundSpec s; s.gameId=90782; s.finalMult=4.72; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_783() { RoundSpec s; s.gameId=90783; s.finalMult=4.78; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_784() { RoundSpec s; s.gameId=90784; s.finalMult=4.84; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_785() { RoundSpec s; s.gameId=90785; s.finalMult=4.90; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_786() { RoundSpec s; s.gameId=90786; s.finalMult=4.96; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_787() { RoundSpec s; s.gameId=90787; s.finalMult=5.02; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_788() { RoundSpec s; s.gameId=90788; s.finalMult=5.08; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_789() { RoundSpec s; s.gameId=90789; s.finalMult=5.14; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_790() { RoundSpec s; s.gameId=90790; s.finalMult=5.20; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_791() { RoundSpec s; s.gameId=90791; s.finalMult=5.26; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_792() { RoundSpec s; s.gameId=90792; s.finalMult=5.32; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_793() { RoundSpec s; s.gameId=90793; s.finalMult=5.38; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_794() { RoundSpec s; s.gameId=90794; s.finalMult=5.44; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_795() { RoundSpec s; s.gameId=90795; s.finalMult=5.50; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_796() { RoundSpec s; s.gameId=90796; s.finalMult=5.56; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_797() { RoundSpec s; s.gameId=90797; s.finalMult=5.62; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_798() { RoundSpec s; s.gameId=90798; s.finalMult=5.68; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_799() { RoundSpec s; s.gameId=90799; s.finalMult=5.74; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_800() { RoundSpec s; s.gameId=90800; s.finalMult=5.80; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_801() { RoundSpec s; s.gameId=90801; s.finalMult=5.86; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_802() { RoundSpec s; s.gameId=90802; s.finalMult=5.92; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_803() { RoundSpec s; s.gameId=90803; s.finalMult=5.98; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_804() { RoundSpec s; s.gameId=90804; s.finalMult=6.04; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_805() { RoundSpec s; s.gameId=90805; s.finalMult=6.10; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_806() { RoundSpec s; s.gameId=90806; s.finalMult=6.16; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_807() { RoundSpec s; s.gameId=90807; s.finalMult=6.22; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_808() { RoundSpec s; s.gameId=90808; s.finalMult=6.28; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_809() { RoundSpec s; s.gameId=90809; s.finalMult=6.34; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_810() { RoundSpec s; s.gameId=90810; s.finalMult=6.40; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_811() { RoundSpec s; s.gameId=90811; s.finalMult=6.46; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_812() { RoundSpec s; s.gameId=90812; s.finalMult=6.52; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_813() { RoundSpec s; s.gameId=90813; s.finalMult=6.58; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_814() { RoundSpec s; s.gameId=90814; s.finalMult=6.64; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_815() { RoundSpec s; s.gameId=90815; s.finalMult=6.70; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_816() { RoundSpec s; s.gameId=90816; s.finalMult=6.76; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_817() { RoundSpec s; s.gameId=90817; s.finalMult=6.82; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_818() { RoundSpec s; s.gameId=90818; s.finalMult=6.88; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_819() { RoundSpec s; s.gameId=90819; s.finalMult=6.94; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_820() { RoundSpec s; s.gameId=90820; s.finalMult=7.00; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_821() { RoundSpec s; s.gameId=90821; s.finalMult=7.06; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_822() { RoundSpec s; s.gameId=90822; s.finalMult=7.12; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_823() { RoundSpec s; s.gameId=90823; s.finalMult=7.18; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_824() { RoundSpec s; s.gameId=90824; s.finalMult=7.24; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_825() { RoundSpec s; s.gameId=90825; s.finalMult=7.30; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_826() { RoundSpec s; s.gameId=90826; s.finalMult=7.36; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_827() { RoundSpec s; s.gameId=90827; s.finalMult=7.42; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_828() { RoundSpec s; s.gameId=90828; s.finalMult=7.48; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_829() { RoundSpec s; s.gameId=90829; s.finalMult=7.54; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_830() { RoundSpec s; s.gameId=90830; s.finalMult=7.60; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_831() { RoundSpec s; s.gameId=90831; s.finalMult=7.66; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_832() { RoundSpec s; s.gameId=90832; s.finalMult=7.72; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_833() { RoundSpec s; s.gameId=90833; s.finalMult=7.78; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_834() { RoundSpec s; s.gameId=90834; s.finalMult=7.84; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_835() { RoundSpec s; s.gameId=90835; s.finalMult=7.90; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_836() { RoundSpec s; s.gameId=90836; s.finalMult=7.96; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_837() { RoundSpec s; s.gameId=90837; s.finalMult=8.02; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_838() { RoundSpec s; s.gameId=90838; s.finalMult=8.08; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_839() { RoundSpec s; s.gameId=90839; s.finalMult=8.14; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_840() { RoundSpec s; s.gameId=90840; s.finalMult=1.00; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_841() { RoundSpec s; s.gameId=90841; s.finalMult=1.06; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_842() { RoundSpec s; s.gameId=90842; s.finalMult=1.12; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_843() { RoundSpec s; s.gameId=90843; s.finalMult=1.18; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_844() { RoundSpec s; s.gameId=90844; s.finalMult=1.24; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_845() { RoundSpec s; s.gameId=90845; s.finalMult=1.30; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_846() { RoundSpec s; s.gameId=90846; s.finalMult=1.36; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_847() { RoundSpec s; s.gameId=90847; s.finalMult=1.42; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_848() { RoundSpec s; s.gameId=90848; s.finalMult=1.48; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_849() { RoundSpec s; s.gameId=90849; s.finalMult=1.54; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_850() { RoundSpec s; s.gameId=90850; s.finalMult=1.60; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_851() { RoundSpec s; s.gameId=90851; s.finalMult=1.66; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_852() { RoundSpec s; s.gameId=90852; s.finalMult=1.72; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_853() { RoundSpec s; s.gameId=90853; s.finalMult=1.78; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_854() { RoundSpec s; s.gameId=90854; s.finalMult=1.84; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_855() { RoundSpec s; s.gameId=90855; s.finalMult=1.90; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_856() { RoundSpec s; s.gameId=90856; s.finalMult=1.96; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_857() { RoundSpec s; s.gameId=90857; s.finalMult=2.02; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_858() { RoundSpec s; s.gameId=90858; s.finalMult=2.08; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_859() { RoundSpec s; s.gameId=90859; s.finalMult=2.14; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_860() { RoundSpec s; s.gameId=90860; s.finalMult=2.20; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_861() { RoundSpec s; s.gameId=90861; s.finalMult=2.26; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_862() { RoundSpec s; s.gameId=90862; s.finalMult=2.32; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_863() { RoundSpec s; s.gameId=90863; s.finalMult=2.38; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_864() { RoundSpec s; s.gameId=90864; s.finalMult=2.44; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_865() { RoundSpec s; s.gameId=90865; s.finalMult=2.50; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_866() { RoundSpec s; s.gameId=90866; s.finalMult=2.56; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_867() { RoundSpec s; s.gameId=90867; s.finalMult=2.62; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_868() { RoundSpec s; s.gameId=90868; s.finalMult=2.68; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_869() { RoundSpec s; s.gameId=90869; s.finalMult=2.74; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_870() { RoundSpec s; s.gameId=90870; s.finalMult=2.80; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_871() { RoundSpec s; s.gameId=90871; s.finalMult=2.86; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_872() { RoundSpec s; s.gameId=90872; s.finalMult=2.92; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_873() { RoundSpec s; s.gameId=90873; s.finalMult=2.98; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_874() { RoundSpec s; s.gameId=90874; s.finalMult=3.04; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_875() { RoundSpec s; s.gameId=90875; s.finalMult=3.10; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_876() { RoundSpec s; s.gameId=90876; s.finalMult=3.16; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_877() { RoundSpec s; s.gameId=90877; s.finalMult=3.22; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_878() { RoundSpec s; s.gameId=90878; s.finalMult=3.28; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_879() { RoundSpec s; s.gameId=90879; s.finalMult=3.34; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_880() { RoundSpec s; s.gameId=90880; s.finalMult=3.40; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_881() { RoundSpec s; s.gameId=90881; s.finalMult=3.46; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_882() { RoundSpec s; s.gameId=90882; s.finalMult=3.52; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_883() { RoundSpec s; s.gameId=90883; s.finalMult=3.58; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_884() { RoundSpec s; s.gameId=90884; s.finalMult=3.64; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_885() { RoundSpec s; s.gameId=90885; s.finalMult=3.70; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_886() { RoundSpec s; s.gameId=90886; s.finalMult=3.76; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_887() { RoundSpec s; s.gameId=90887; s.finalMult=3.82; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_888() { RoundSpec s; s.gameId=90888; s.finalMult=3.88; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_889() { RoundSpec s; s.gameId=90889; s.finalMult=3.94; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_890() { RoundSpec s; s.gameId=90890; s.finalMult=4.00; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_891() { RoundSpec s; s.gameId=90891; s.finalMult=4.06; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_892() { RoundSpec s; s.gameId=90892; s.finalMult=4.12; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_893() { RoundSpec s; s.gameId=90893; s.finalMult=4.18; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_894() { RoundSpec s; s.gameId=90894; s.finalMult=4.24; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_895() { RoundSpec s; s.gameId=90895; s.finalMult=4.30; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_896() { RoundSpec s; s.gameId=90896; s.finalMult=4.36; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_897() { RoundSpec s; s.gameId=90897; s.finalMult=4.42; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_898() { RoundSpec s; s.gameId=90898; s.finalMult=4.48; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_899() { RoundSpec s; s.gameId=90899; s.finalMult=4.54; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_900() { RoundSpec s; s.gameId=90900; s.finalMult=4.60; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_901() { RoundSpec s; s.gameId=90901; s.finalMult=4.66; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_902() { RoundSpec s; s.gameId=90902; s.finalMult=4.72; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_903() { RoundSpec s; s.gameId=90903; s.finalMult=4.78; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_904() { RoundSpec s; s.gameId=90904; s.finalMult=4.84; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_905() { RoundSpec s; s.gameId=90905; s.finalMult=4.90; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_906() { RoundSpec s; s.gameId=90906; s.finalMult=4.96; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_907() { RoundSpec s; s.gameId=90907; s.finalMult=5.02; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_908() { RoundSpec s; s.gameId=90908; s.finalMult=5.08; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_909() { RoundSpec s; s.gameId=90909; s.finalMult=5.14; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_910() { RoundSpec s; s.gameId=90910; s.finalMult=5.20; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_911() { RoundSpec s; s.gameId=90911; s.finalMult=5.26; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_912() { RoundSpec s; s.gameId=90912; s.finalMult=5.32; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_913() { RoundSpec s; s.gameId=90913; s.finalMult=5.38; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_914() { RoundSpec s; s.gameId=90914; s.finalMult=5.44; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_915() { RoundSpec s; s.gameId=90915; s.finalMult=5.50; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_916() { RoundSpec s; s.gameId=90916; s.finalMult=5.56; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_917() { RoundSpec s; s.gameId=90917; s.finalMult=5.62; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_918() { RoundSpec s; s.gameId=90918; s.finalMult=5.68; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_919() { RoundSpec s; s.gameId=90919; s.finalMult=5.74; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_920() { RoundSpec s; s.gameId=90920; s.finalMult=5.80; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_921() { RoundSpec s; s.gameId=90921; s.finalMult=5.86; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_922() { RoundSpec s; s.gameId=90922; s.finalMult=5.92; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_923() { RoundSpec s; s.gameId=90923; s.finalMult=5.98; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_924() { RoundSpec s; s.gameId=90924; s.finalMult=6.04; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_925() { RoundSpec s; s.gameId=90925; s.finalMult=6.10; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_926() { RoundSpec s; s.gameId=90926; s.finalMult=6.16; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_927() { RoundSpec s; s.gameId=90927; s.finalMult=6.22; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_928() { RoundSpec s; s.gameId=90928; s.finalMult=6.28; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_929() { RoundSpec s; s.gameId=90929; s.finalMult=6.34; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_930() { RoundSpec s; s.gameId=90930; s.finalMult=6.40; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_931() { RoundSpec s; s.gameId=90931; s.finalMult=6.46; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_932() { RoundSpec s; s.gameId=90932; s.finalMult=6.52; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_933() { RoundSpec s; s.gameId=90933; s.finalMult=6.58; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_934() { RoundSpec s; s.gameId=90934; s.finalMult=6.64; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_935() { RoundSpec s; s.gameId=90935; s.finalMult=6.70; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_936() { RoundSpec s; s.gameId=90936; s.finalMult=6.76; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_937() { RoundSpec s; s.gameId=90937; s.finalMult=6.82; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_938() { RoundSpec s; s.gameId=90938; s.finalMult=6.88; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_939() { RoundSpec s; s.gameId=90939; s.finalMult=6.94; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_940() { RoundSpec s; s.gameId=90940; s.finalMult=7.00; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_941() { RoundSpec s; s.gameId=90941; s.finalMult=7.06; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_942() { RoundSpec s; s.gameId=90942; s.finalMult=7.12; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_943() { RoundSpec s; s.gameId=90943; s.finalMult=7.18; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_944() { RoundSpec s; s.gameId=90944; s.finalMult=7.24; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_945() { RoundSpec s; s.gameId=90945; s.finalMult=7.30; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_946() { RoundSpec s; s.gameId=90946; s.finalMult=7.36; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_947() { RoundSpec s; s.gameId=90947; s.finalMult=7.42; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_948() { RoundSpec s; s.gameId=90948; s.finalMult=7.48; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_949() { RoundSpec s; s.gameId=90949; s.finalMult=7.54; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_950() { RoundSpec s; s.gameId=90950; s.finalMult=7.60; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_951() { RoundSpec s; s.gameId=90951; s.finalMult=7.66; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_952() { RoundSpec s; s.gameId=90952; s.finalMult=7.72; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_953() { RoundSpec s; s.gameId=90953; s.finalMult=7.78; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_954() { RoundSpec s; s.gameId=90954; s.finalMult=7.84; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_955() { RoundSpec s; s.gameId=90955; s.finalMult=7.90; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_956() { RoundSpec s; s.gameId=90956; s.finalMult=7.96; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_957() { RoundSpec s; s.gameId=90957; s.finalMult=8.02; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_958() { RoundSpec s; s.gameId=90958; s.finalMult=8.08; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_959() { RoundSpec s; s.gameId=90959; s.finalMult=8.14; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_960() { RoundSpec s; s.gameId=90960; s.finalMult=1.00; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_961() { RoundSpec s; s.gameId=90961; s.finalMult=1.06; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_962() { RoundSpec s; s.gameId=90962; s.finalMult=1.12; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_963() { RoundSpec s; s.gameId=90963; s.finalMult=1.18; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_964() { RoundSpec s; s.gameId=90964; s.finalMult=1.24; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_965() { RoundSpec s; s.gameId=90965; s.finalMult=1.30; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_966() { RoundSpec s; s.gameId=90966; s.finalMult=1.36; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_967() { RoundSpec s; s.gameId=90967; s.finalMult=1.42; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_968() { RoundSpec s; s.gameId=90968; s.finalMult=1.48; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_969() { RoundSpec s; s.gameId=90969; s.finalMult=1.54; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_970() { RoundSpec s; s.gameId=90970; s.finalMult=1.60; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_971() { RoundSpec s; s.gameId=90971; s.finalMult=1.66; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_972() { RoundSpec s; s.gameId=90972; s.finalMult=1.72; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_973() { RoundSpec s; s.gameId=90973; s.finalMult=1.78; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_974() { RoundSpec s; s.gameId=90974; s.finalMult=1.84; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_975() { RoundSpec s; s.gameId=90975; s.finalMult=1.90; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_976() { RoundSpec s; s.gameId=90976; s.finalMult=1.96; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_977() { RoundSpec s; s.gameId=90977; s.finalMult=2.02; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_978() { RoundSpec s; s.gameId=90978; s.finalMult=2.08; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_979() { RoundSpec s; s.gameId=90979; s.finalMult=2.14; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_980() { RoundSpec s; s.gameId=90980; s.finalMult=2.20; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_981() { RoundSpec s; s.gameId=90981; s.finalMult=2.26; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_982() { RoundSpec s; s.gameId=90982; s.finalMult=2.32; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_983() { RoundSpec s; s.gameId=90983; s.finalMult=2.38; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_984() { RoundSpec s; s.gameId=90984; s.finalMult=2.44; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_985() { RoundSpec s; s.gameId=90985; s.finalMult=2.50; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_986() { RoundSpec s; s.gameId=90986; s.finalMult=2.56; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_987() { RoundSpec s; s.gameId=90987; s.finalMult=2.62; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_988() { RoundSpec s; s.gameId=90988; s.finalMult=2.68; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_989() { RoundSpec s; s.gameId=90989; s.finalMult=2.74; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_990() { RoundSpec s; s.gameId=90990; s.finalMult=2.80; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_991() { RoundSpec s; s.gameId=90991; s.finalMult=2.86; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_992() { RoundSpec s; s.gameId=90992; s.finalMult=2.92; s.progressTicks=4; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_993() { RoundSpec s; s.gameId=90993; s.finalMult=2.98; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_994() { RoundSpec s; s.gameId=90994; s.finalMult=3.04; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_995() { RoundSpec s; s.gameId=90995; s.finalMult=3.10; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_996() { RoundSpec s; s.gameId=90996; s.finalMult=3.16; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_997() { RoundSpec s; s.gameId=90997; s.finalMult=3.22; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_998() { RoundSpec s; s.gameId=90998; s.finalMult=3.28; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_999() { RoundSpec s; s.gameId=90999; s.finalMult=3.34; s.progressTicks=11; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1000() { RoundSpec s; s.gameId=91000; s.finalMult=3.40; s.progressTicks=4; return makeRound(s); }
inline int countFixturesExt4() { return 300; }
}
