#pragma once
#include "ingestion/test_fixtures.hpp"
namespace crashcore::fixtures {
inline std::vector<std::vector<std::uint8_t>> fixture_round_1001() { RoundSpec s; s.gameId=111001; s.finalMult=1.15; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1002() { RoundSpec s; s.gameId=111002; s.finalMult=1.30; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1003() { RoundSpec s; s.gameId=111003; s.finalMult=1.45; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1004() { RoundSpec s; s.gameId=111004; s.finalMult=1.60; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1005() { RoundSpec s; s.gameId=111005; s.finalMult=1.75; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1006() { RoundSpec s; s.gameId=111006; s.finalMult=1.90; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1007() { RoundSpec s; s.gameId=111007; s.finalMult=2.05; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1008() { RoundSpec s; s.gameId=111008; s.finalMult=2.20; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1009() { RoundSpec s; s.gameId=111009; s.finalMult=2.35; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1010() { RoundSpec s; s.gameId=111010; s.finalMult=2.50; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1011() { RoundSpec s; s.gameId=111011; s.finalMult=2.65; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1012() { RoundSpec s; s.gameId=111012; s.finalMult=2.80; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1013() { RoundSpec s; s.gameId=111013; s.finalMult=2.95; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1014() { RoundSpec s; s.gameId=111014; s.finalMult=3.10; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1015() { RoundSpec s; s.gameId=111015; s.finalMult=3.25; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1016() { RoundSpec s; s.gameId=111016; s.finalMult=3.40; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1017() { RoundSpec s; s.gameId=111017; s.finalMult=3.55; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1018() { RoundSpec s; s.gameId=111018; s.finalMult=3.70; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1019() { RoundSpec s; s.gameId=111019; s.finalMult=3.85; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1020() { RoundSpec s; s.gameId=111020; s.finalMult=4.00; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1021() { RoundSpec s; s.gameId=111021; s.finalMult=4.15; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1022() { RoundSpec s; s.gameId=111022; s.finalMult=4.30; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1023() { RoundSpec s; s.gameId=111023; s.finalMult=4.45; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1024() { RoundSpec s; s.gameId=111024; s.finalMult=4.60; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1025() { RoundSpec s; s.gameId=111025; s.finalMult=4.75; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1026() { RoundSpec s; s.gameId=111026; s.finalMult=4.90; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1027() { RoundSpec s; s.gameId=111027; s.finalMult=5.05; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1028() { RoundSpec s; s.gameId=111028; s.finalMult=5.20; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1029() { RoundSpec s; s.gameId=111029; s.finalMult=5.35; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1030() { RoundSpec s; s.gameId=111030; s.finalMult=5.50; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1031() { RoundSpec s; s.gameId=111031; s.finalMult=5.65; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1032() { RoundSpec s; s.gameId=111032; s.finalMult=5.80; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1033() { RoundSpec s; s.gameId=111033; s.finalMult=5.95; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1034() { RoundSpec s; s.gameId=111034; s.finalMult=6.10; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1035() { RoundSpec s; s.gameId=111035; s.finalMult=6.25; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1036() { RoundSpec s; s.gameId=111036; s.finalMult=6.40; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1037() { RoundSpec s; s.gameId=111037; s.finalMult=6.55; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1038() { RoundSpec s; s.gameId=111038; s.finalMult=6.70; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1039() { RoundSpec s; s.gameId=111039; s.finalMult=6.85; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1040() { RoundSpec s; s.gameId=111040; s.finalMult=7.00; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1041() { RoundSpec s; s.gameId=111041; s.finalMult=7.15; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1042() { RoundSpec s; s.gameId=111042; s.finalMult=7.30; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1043() { RoundSpec s; s.gameId=111043; s.finalMult=7.45; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1044() { RoundSpec s; s.gameId=111044; s.finalMult=7.60; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1045() { RoundSpec s; s.gameId=111045; s.finalMult=7.75; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1046() { RoundSpec s; s.gameId=111046; s.finalMult=7.90; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1047() { RoundSpec s; s.gameId=111047; s.finalMult=8.05; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1048() { RoundSpec s; s.gameId=111048; s.finalMult=8.20; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1049() { RoundSpec s; s.gameId=111049; s.finalMult=8.35; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1050() { RoundSpec s; s.gameId=111050; s.finalMult=1.00; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1051() { RoundSpec s; s.gameId=111051; s.finalMult=1.15; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1052() { RoundSpec s; s.gameId=111052; s.finalMult=1.30; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1053() { RoundSpec s; s.gameId=111053; s.finalMult=1.45; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1054() { RoundSpec s; s.gameId=111054; s.finalMult=1.60; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1055() { RoundSpec s; s.gameId=111055; s.finalMult=1.75; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1056() { RoundSpec s; s.gameId=111056; s.finalMult=1.90; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1057() { RoundSpec s; s.gameId=111057; s.finalMult=2.05; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1058() { RoundSpec s; s.gameId=111058; s.finalMult=2.20; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1059() { RoundSpec s; s.gameId=111059; s.finalMult=2.35; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1060() { RoundSpec s; s.gameId=111060; s.finalMult=2.50; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1061() { RoundSpec s; s.gameId=111061; s.finalMult=2.65; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1062() { RoundSpec s; s.gameId=111062; s.finalMult=2.80; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1063() { RoundSpec s; s.gameId=111063; s.finalMult=2.95; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1064() { RoundSpec s; s.gameId=111064; s.finalMult=3.10; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1065() { RoundSpec s; s.gameId=111065; s.finalMult=3.25; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1066() { RoundSpec s; s.gameId=111066; s.finalMult=3.40; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1067() { RoundSpec s; s.gameId=111067; s.finalMult=3.55; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1068() { RoundSpec s; s.gameId=111068; s.finalMult=3.70; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1069() { RoundSpec s; s.gameId=111069; s.finalMult=3.85; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1070() { RoundSpec s; s.gameId=111070; s.finalMult=4.00; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1071() { RoundSpec s; s.gameId=111071; s.finalMult=4.15; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1072() { RoundSpec s; s.gameId=111072; s.finalMult=4.30; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1073() { RoundSpec s; s.gameId=111073; s.finalMult=4.45; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1074() { RoundSpec s; s.gameId=111074; s.finalMult=4.60; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1075() { RoundSpec s; s.gameId=111075; s.finalMult=4.75; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1076() { RoundSpec s; s.gameId=111076; s.finalMult=4.90; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1077() { RoundSpec s; s.gameId=111077; s.finalMult=5.05; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1078() { RoundSpec s; s.gameId=111078; s.finalMult=5.20; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1079() { RoundSpec s; s.gameId=111079; s.finalMult=5.35; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1080() { RoundSpec s; s.gameId=111080; s.finalMult=5.50; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1081() { RoundSpec s; s.gameId=111081; s.finalMult=5.65; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1082() { RoundSpec s; s.gameId=111082; s.finalMult=5.80; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1083() { RoundSpec s; s.gameId=111083; s.finalMult=5.95; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1084() { RoundSpec s; s.gameId=111084; s.finalMult=6.10; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1085() { RoundSpec s; s.gameId=111085; s.finalMult=6.25; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1086() { RoundSpec s; s.gameId=111086; s.finalMult=6.40; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1087() { RoundSpec s; s.gameId=111087; s.finalMult=6.55; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1088() { RoundSpec s; s.gameId=111088; s.finalMult=6.70; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1089() { RoundSpec s; s.gameId=111089; s.finalMult=6.85; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1090() { RoundSpec s; s.gameId=111090; s.finalMult=7.00; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1091() { RoundSpec s; s.gameId=111091; s.finalMult=7.15; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1092() { RoundSpec s; s.gameId=111092; s.finalMult=7.30; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1093() { RoundSpec s; s.gameId=111093; s.finalMult=7.45; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1094() { RoundSpec s; s.gameId=111094; s.finalMult=7.60; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1095() { RoundSpec s; s.gameId=111095; s.finalMult=7.75; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1096() { RoundSpec s; s.gameId=111096; s.finalMult=7.90; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1097() { RoundSpec s; s.gameId=111097; s.finalMult=8.05; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1098() { RoundSpec s; s.gameId=111098; s.finalMult=8.20; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1099() { RoundSpec s; s.gameId=111099; s.finalMult=8.35; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1100() { RoundSpec s; s.gameId=111100; s.finalMult=1.00; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1101() { RoundSpec s; s.gameId=111101; s.finalMult=1.15; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1102() { RoundSpec s; s.gameId=111102; s.finalMult=1.30; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1103() { RoundSpec s; s.gameId=111103; s.finalMult=1.45; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1104() { RoundSpec s; s.gameId=111104; s.finalMult=1.60; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1105() { RoundSpec s; s.gameId=111105; s.finalMult=1.75; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1106() { RoundSpec s; s.gameId=111106; s.finalMult=1.90; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1107() { RoundSpec s; s.gameId=111107; s.finalMult=2.05; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1108() { RoundSpec s; s.gameId=111108; s.finalMult=2.20; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1109() { RoundSpec s; s.gameId=111109; s.finalMult=2.35; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1110() { RoundSpec s; s.gameId=111110; s.finalMult=2.50; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1111() { RoundSpec s; s.gameId=111111; s.finalMult=2.65; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1112() { RoundSpec s; s.gameId=111112; s.finalMult=2.80; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1113() { RoundSpec s; s.gameId=111113; s.finalMult=2.95; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1114() { RoundSpec s; s.gameId=111114; s.finalMult=3.10; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1115() { RoundSpec s; s.gameId=111115; s.finalMult=3.25; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1116() { RoundSpec s; s.gameId=111116; s.finalMult=3.40; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1117() { RoundSpec s; s.gameId=111117; s.finalMult=3.55; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1118() { RoundSpec s; s.gameId=111118; s.finalMult=3.70; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1119() { RoundSpec s; s.gameId=111119; s.finalMult=3.85; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1120() { RoundSpec s; s.gameId=111120; s.finalMult=4.00; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1121() { RoundSpec s; s.gameId=111121; s.finalMult=4.15; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1122() { RoundSpec s; s.gameId=111122; s.finalMult=4.30; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1123() { RoundSpec s; s.gameId=111123; s.finalMult=4.45; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1124() { RoundSpec s; s.gameId=111124; s.finalMult=4.60; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1125() { RoundSpec s; s.gameId=111125; s.finalMult=4.75; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1126() { RoundSpec s; s.gameId=111126; s.finalMult=4.90; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1127() { RoundSpec s; s.gameId=111127; s.finalMult=5.05; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1128() { RoundSpec s; s.gameId=111128; s.finalMult=5.20; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1129() { RoundSpec s; s.gameId=111129; s.finalMult=5.35; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1130() { RoundSpec s; s.gameId=111130; s.finalMult=5.50; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1131() { RoundSpec s; s.gameId=111131; s.finalMult=5.65; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1132() { RoundSpec s; s.gameId=111132; s.finalMult=5.80; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1133() { RoundSpec s; s.gameId=111133; s.finalMult=5.95; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1134() { RoundSpec s; s.gameId=111134; s.finalMult=6.10; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1135() { RoundSpec s; s.gameId=111135; s.finalMult=6.25; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1136() { RoundSpec s; s.gameId=111136; s.finalMult=6.40; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1137() { RoundSpec s; s.gameId=111137; s.finalMult=6.55; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1138() { RoundSpec s; s.gameId=111138; s.finalMult=6.70; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1139() { RoundSpec s; s.gameId=111139; s.finalMult=6.85; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1140() { RoundSpec s; s.gameId=111140; s.finalMult=7.00; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1141() { RoundSpec s; s.gameId=111141; s.finalMult=7.15; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1142() { RoundSpec s; s.gameId=111142; s.finalMult=7.30; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1143() { RoundSpec s; s.gameId=111143; s.finalMult=7.45; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1144() { RoundSpec s; s.gameId=111144; s.finalMult=7.60; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1145() { RoundSpec s; s.gameId=111145; s.finalMult=7.75; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1146() { RoundSpec s; s.gameId=111146; s.finalMult=7.90; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1147() { RoundSpec s; s.gameId=111147; s.finalMult=8.05; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1148() { RoundSpec s; s.gameId=111148; s.finalMult=8.20; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1149() { RoundSpec s; s.gameId=111149; s.finalMult=8.35; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1150() { RoundSpec s; s.gameId=111150; s.finalMult=1.00; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1151() { RoundSpec s; s.gameId=111151; s.finalMult=1.15; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1152() { RoundSpec s; s.gameId=111152; s.finalMult=1.30; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1153() { RoundSpec s; s.gameId=111153; s.finalMult=1.45; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1154() { RoundSpec s; s.gameId=111154; s.finalMult=1.60; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1155() { RoundSpec s; s.gameId=111155; s.finalMult=1.75; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1156() { RoundSpec s; s.gameId=111156; s.finalMult=1.90; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1157() { RoundSpec s; s.gameId=111157; s.finalMult=2.05; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1158() { RoundSpec s; s.gameId=111158; s.finalMult=2.20; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1159() { RoundSpec s; s.gameId=111159; s.finalMult=2.35; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1160() { RoundSpec s; s.gameId=111160; s.finalMult=2.50; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1161() { RoundSpec s; s.gameId=111161; s.finalMult=2.65; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1162() { RoundSpec s; s.gameId=111162; s.finalMult=2.80; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1163() { RoundSpec s; s.gameId=111163; s.finalMult=2.95; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1164() { RoundSpec s; s.gameId=111164; s.finalMult=3.10; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1165() { RoundSpec s; s.gameId=111165; s.finalMult=3.25; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1166() { RoundSpec s; s.gameId=111166; s.finalMult=3.40; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1167() { RoundSpec s; s.gameId=111167; s.finalMult=3.55; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1168() { RoundSpec s; s.gameId=111168; s.finalMult=3.70; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1169() { RoundSpec s; s.gameId=111169; s.finalMult=3.85; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1170() { RoundSpec s; s.gameId=111170; s.finalMult=4.00; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1171() { RoundSpec s; s.gameId=111171; s.finalMult=4.15; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1172() { RoundSpec s; s.gameId=111172; s.finalMult=4.30; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1173() { RoundSpec s; s.gameId=111173; s.finalMult=4.45; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1174() { RoundSpec s; s.gameId=111174; s.finalMult=4.60; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1175() { RoundSpec s; s.gameId=111175; s.finalMult=4.75; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1176() { RoundSpec s; s.gameId=111176; s.finalMult=4.90; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1177() { RoundSpec s; s.gameId=111177; s.finalMult=5.05; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1178() { RoundSpec s; s.gameId=111178; s.finalMult=5.20; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1179() { RoundSpec s; s.gameId=111179; s.finalMult=5.35; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1180() { RoundSpec s; s.gameId=111180; s.finalMult=5.50; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1181() { RoundSpec s; s.gameId=111181; s.finalMult=5.65; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1182() { RoundSpec s; s.gameId=111182; s.finalMult=5.80; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1183() { RoundSpec s; s.gameId=111183; s.finalMult=5.95; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1184() { RoundSpec s; s.gameId=111184; s.finalMult=6.10; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1185() { RoundSpec s; s.gameId=111185; s.finalMult=6.25; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1186() { RoundSpec s; s.gameId=111186; s.finalMult=6.40; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1187() { RoundSpec s; s.gameId=111187; s.finalMult=6.55; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1188() { RoundSpec s; s.gameId=111188; s.finalMult=6.70; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1189() { RoundSpec s; s.gameId=111189; s.finalMult=6.85; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1190() { RoundSpec s; s.gameId=111190; s.finalMult=7.00; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1191() { RoundSpec s; s.gameId=111191; s.finalMult=7.15; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1192() { RoundSpec s; s.gameId=111192; s.finalMult=7.30; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1193() { RoundSpec s; s.gameId=111193; s.finalMult=7.45; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1194() { RoundSpec s; s.gameId=111194; s.finalMult=7.60; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1195() { RoundSpec s; s.gameId=111195; s.finalMult=7.75; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1196() { RoundSpec s; s.gameId=111196; s.finalMult=7.90; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1197() { RoundSpec s; s.gameId=111197; s.finalMult=8.05; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1198() { RoundSpec s; s.gameId=111198; s.finalMult=8.20; s.progressTicks=9; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1199() { RoundSpec s; s.gameId=111199; s.finalMult=8.35; s.progressTicks=10; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1200() { RoundSpec s; s.gameId=111200; s.finalMult=1.00; s.progressTicks=5; return makeRound(s); }
inline int countFixturesExt5() { return 200; }
}
