#pragma once
#include "ingestion/test_fixtures.hpp"
namespace crashcore::fixtures {
inline std::vector<std::vector<std::uint8_t>> fixture_round_1201() { RoundSpec s; s.gameId=131201; s.finalMult=1.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1202() { RoundSpec s; s.gameId=131202; s.finalMult=1.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1203() { RoundSpec s; s.gameId=131203; s.finalMult=1.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1204() { RoundSpec s; s.gameId=131204; s.finalMult=2.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1205() { RoundSpec s; s.gameId=131205; s.finalMult=2.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1206() { RoundSpec s; s.gameId=131206; s.finalMult=2.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1207() { RoundSpec s; s.gameId=131207; s.finalMult=2.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1208() { RoundSpec s; s.gameId=131208; s.finalMult=3.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1209() { RoundSpec s; s.gameId=131209; s.finalMult=3.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1210() { RoundSpec s; s.gameId=131210; s.finalMult=3.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1211() { RoundSpec s; s.gameId=131211; s.finalMult=3.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1212() { RoundSpec s; s.gameId=131212; s.finalMult=4.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1213() { RoundSpec s; s.gameId=131213; s.finalMult=4.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1214() { RoundSpec s; s.gameId=131214; s.finalMult=4.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1215() { RoundSpec s; s.gameId=131215; s.finalMult=4.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1216() { RoundSpec s; s.gameId=131216; s.finalMult=5.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1217() { RoundSpec s; s.gameId=131217; s.finalMult=5.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1218() { RoundSpec s; s.gameId=131218; s.finalMult=5.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1219() { RoundSpec s; s.gameId=131219; s.finalMult=5.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1220() { RoundSpec s; s.gameId=131220; s.finalMult=6.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1221() { RoundSpec s; s.gameId=131221; s.finalMult=6.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1222() { RoundSpec s; s.gameId=131222; s.finalMult=6.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1223() { RoundSpec s; s.gameId=131223; s.finalMult=6.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1224() { RoundSpec s; s.gameId=131224; s.finalMult=7.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1225() { RoundSpec s; s.gameId=131225; s.finalMult=7.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1226() { RoundSpec s; s.gameId=131226; s.finalMult=7.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1227() { RoundSpec s; s.gameId=131227; s.finalMult=7.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1228() { RoundSpec s; s.gameId=131228; s.finalMult=8.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1229() { RoundSpec s; s.gameId=131229; s.finalMult=8.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1230() { RoundSpec s; s.gameId=131230; s.finalMult=1.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1231() { RoundSpec s; s.gameId=131231; s.finalMult=1.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1232() { RoundSpec s; s.gameId=131232; s.finalMult=1.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1233() { RoundSpec s; s.gameId=131233; s.finalMult=1.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1234() { RoundSpec s; s.gameId=131234; s.finalMult=2.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1235() { RoundSpec s; s.gameId=131235; s.finalMult=2.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1236() { RoundSpec s; s.gameId=131236; s.finalMult=2.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1237() { RoundSpec s; s.gameId=131237; s.finalMult=2.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1238() { RoundSpec s; s.gameId=131238; s.finalMult=3.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1239() { RoundSpec s; s.gameId=131239; s.finalMult=3.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1240() { RoundSpec s; s.gameId=131240; s.finalMult=3.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1241() { RoundSpec s; s.gameId=131241; s.finalMult=3.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1242() { RoundSpec s; s.gameId=131242; s.finalMult=4.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1243() { RoundSpec s; s.gameId=131243; s.finalMult=4.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1244() { RoundSpec s; s.gameId=131244; s.finalMult=4.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1245() { RoundSpec s; s.gameId=131245; s.finalMult=4.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1246() { RoundSpec s; s.gameId=131246; s.finalMult=5.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1247() { RoundSpec s; s.gameId=131247; s.finalMult=5.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1248() { RoundSpec s; s.gameId=131248; s.finalMult=5.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1249() { RoundSpec s; s.gameId=131249; s.finalMult=5.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1250() { RoundSpec s; s.gameId=131250; s.finalMult=6.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1251() { RoundSpec s; s.gameId=131251; s.finalMult=6.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1252() { RoundSpec s; s.gameId=131252; s.finalMult=6.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1253() { RoundSpec s; s.gameId=131253; s.finalMult=6.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1254() { RoundSpec s; s.gameId=131254; s.finalMult=7.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1255() { RoundSpec s; s.gameId=131255; s.finalMult=7.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1256() { RoundSpec s; s.gameId=131256; s.finalMult=7.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1257() { RoundSpec s; s.gameId=131257; s.finalMult=7.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1258() { RoundSpec s; s.gameId=131258; s.finalMult=8.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1259() { RoundSpec s; s.gameId=131259; s.finalMult=8.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1260() { RoundSpec s; s.gameId=131260; s.finalMult=1.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1261() { RoundSpec s; s.gameId=131261; s.finalMult=1.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1262() { RoundSpec s; s.gameId=131262; s.finalMult=1.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1263() { RoundSpec s; s.gameId=131263; s.finalMult=1.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1264() { RoundSpec s; s.gameId=131264; s.finalMult=2.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1265() { RoundSpec s; s.gameId=131265; s.finalMult=2.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1266() { RoundSpec s; s.gameId=131266; s.finalMult=2.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1267() { RoundSpec s; s.gameId=131267; s.finalMult=2.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1268() { RoundSpec s; s.gameId=131268; s.finalMult=3.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1269() { RoundSpec s; s.gameId=131269; s.finalMult=3.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1270() { RoundSpec s; s.gameId=131270; s.finalMult=3.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1271() { RoundSpec s; s.gameId=131271; s.finalMult=3.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1272() { RoundSpec s; s.gameId=131272; s.finalMult=4.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1273() { RoundSpec s; s.gameId=131273; s.finalMult=4.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1274() { RoundSpec s; s.gameId=131274; s.finalMult=4.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1275() { RoundSpec s; s.gameId=131275; s.finalMult=4.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1276() { RoundSpec s; s.gameId=131276; s.finalMult=5.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1277() { RoundSpec s; s.gameId=131277; s.finalMult=5.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1278() { RoundSpec s; s.gameId=131278; s.finalMult=5.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1279() { RoundSpec s; s.gameId=131279; s.finalMult=5.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1280() { RoundSpec s; s.gameId=131280; s.finalMult=6.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1281() { RoundSpec s; s.gameId=131281; s.finalMult=6.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1282() { RoundSpec s; s.gameId=131282; s.finalMult=6.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1283() { RoundSpec s; s.gameId=131283; s.finalMult=6.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1284() { RoundSpec s; s.gameId=131284; s.finalMult=7.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1285() { RoundSpec s; s.gameId=131285; s.finalMult=7.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1286() { RoundSpec s; s.gameId=131286; s.finalMult=7.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1287() { RoundSpec s; s.gameId=131287; s.finalMult=7.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1288() { RoundSpec s; s.gameId=131288; s.finalMult=8.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1289() { RoundSpec s; s.gameId=131289; s.finalMult=8.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1290() { RoundSpec s; s.gameId=131290; s.finalMult=1.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1291() { RoundSpec s; s.gameId=131291; s.finalMult=1.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1292() { RoundSpec s; s.gameId=131292; s.finalMult=1.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1293() { RoundSpec s; s.gameId=131293; s.finalMult=1.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1294() { RoundSpec s; s.gameId=131294; s.finalMult=2.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1295() { RoundSpec s; s.gameId=131295; s.finalMult=2.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1296() { RoundSpec s; s.gameId=131296; s.finalMult=2.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1297() { RoundSpec s; s.gameId=131297; s.finalMult=2.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1298() { RoundSpec s; s.gameId=131298; s.finalMult=3.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1299() { RoundSpec s; s.gameId=131299; s.finalMult=3.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1300() { RoundSpec s; s.gameId=131300; s.finalMult=3.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1301() { RoundSpec s; s.gameId=131301; s.finalMult=3.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1302() { RoundSpec s; s.gameId=131302; s.finalMult=4.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1303() { RoundSpec s; s.gameId=131303; s.finalMult=4.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1304() { RoundSpec s; s.gameId=131304; s.finalMult=4.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1305() { RoundSpec s; s.gameId=131305; s.finalMult=4.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1306() { RoundSpec s; s.gameId=131306; s.finalMult=5.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1307() { RoundSpec s; s.gameId=131307; s.finalMult=5.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1308() { RoundSpec s; s.gameId=131308; s.finalMult=5.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1309() { RoundSpec s; s.gameId=131309; s.finalMult=5.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1310() { RoundSpec s; s.gameId=131310; s.finalMult=6.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1311() { RoundSpec s; s.gameId=131311; s.finalMult=6.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1312() { RoundSpec s; s.gameId=131312; s.finalMult=6.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1313() { RoundSpec s; s.gameId=131313; s.finalMult=6.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1314() { RoundSpec s; s.gameId=131314; s.finalMult=7.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1315() { RoundSpec s; s.gameId=131315; s.finalMult=7.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1316() { RoundSpec s; s.gameId=131316; s.finalMult=7.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1317() { RoundSpec s; s.gameId=131317; s.finalMult=7.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1318() { RoundSpec s; s.gameId=131318; s.finalMult=8.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1319() { RoundSpec s; s.gameId=131319; s.finalMult=8.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1320() { RoundSpec s; s.gameId=131320; s.finalMult=1.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1321() { RoundSpec s; s.gameId=131321; s.finalMult=1.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1322() { RoundSpec s; s.gameId=131322; s.finalMult=1.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1323() { RoundSpec s; s.gameId=131323; s.finalMult=1.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1324() { RoundSpec s; s.gameId=131324; s.finalMult=2.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1325() { RoundSpec s; s.gameId=131325; s.finalMult=2.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1326() { RoundSpec s; s.gameId=131326; s.finalMult=2.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1327() { RoundSpec s; s.gameId=131327; s.finalMult=2.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1328() { RoundSpec s; s.gameId=131328; s.finalMult=3.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1329() { RoundSpec s; s.gameId=131329; s.finalMult=3.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1330() { RoundSpec s; s.gameId=131330; s.finalMult=3.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1331() { RoundSpec s; s.gameId=131331; s.finalMult=3.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1332() { RoundSpec s; s.gameId=131332; s.finalMult=4.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1333() { RoundSpec s; s.gameId=131333; s.finalMult=4.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1334() { RoundSpec s; s.gameId=131334; s.finalMult=4.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1335() { RoundSpec s; s.gameId=131335; s.finalMult=4.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1336() { RoundSpec s; s.gameId=131336; s.finalMult=5.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1337() { RoundSpec s; s.gameId=131337; s.finalMult=5.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1338() { RoundSpec s; s.gameId=131338; s.finalMult=5.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1339() { RoundSpec s; s.gameId=131339; s.finalMult=5.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1340() { RoundSpec s; s.gameId=131340; s.finalMult=6.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1341() { RoundSpec s; s.gameId=131341; s.finalMult=6.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1342() { RoundSpec s; s.gameId=131342; s.finalMult=6.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1343() { RoundSpec s; s.gameId=131343; s.finalMult=6.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1344() { RoundSpec s; s.gameId=131344; s.finalMult=7.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1345() { RoundSpec s; s.gameId=131345; s.finalMult=7.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1346() { RoundSpec s; s.gameId=131346; s.finalMult=7.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1347() { RoundSpec s; s.gameId=131347; s.finalMult=7.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1348() { RoundSpec s; s.gameId=131348; s.finalMult=8.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1349() { RoundSpec s; s.gameId=131349; s.finalMult=8.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1350() { RoundSpec s; s.gameId=131350; s.finalMult=1.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1351() { RoundSpec s; s.gameId=131351; s.finalMult=1.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1352() { RoundSpec s; s.gameId=131352; s.finalMult=1.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1353() { RoundSpec s; s.gameId=131353; s.finalMult=1.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1354() { RoundSpec s; s.gameId=131354; s.finalMult=2.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1355() { RoundSpec s; s.gameId=131355; s.finalMult=2.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1356() { RoundSpec s; s.gameId=131356; s.finalMult=2.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1357() { RoundSpec s; s.gameId=131357; s.finalMult=2.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1358() { RoundSpec s; s.gameId=131358; s.finalMult=3.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1359() { RoundSpec s; s.gameId=131359; s.finalMult=3.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1360() { RoundSpec s; s.gameId=131360; s.finalMult=3.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1361() { RoundSpec s; s.gameId=131361; s.finalMult=3.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1362() { RoundSpec s; s.gameId=131362; s.finalMult=4.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1363() { RoundSpec s; s.gameId=131363; s.finalMult=4.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1364() { RoundSpec s; s.gameId=131364; s.finalMult=4.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1365() { RoundSpec s; s.gameId=131365; s.finalMult=4.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1366() { RoundSpec s; s.gameId=131366; s.finalMult=5.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1367() { RoundSpec s; s.gameId=131367; s.finalMult=5.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1368() { RoundSpec s; s.gameId=131368; s.finalMult=5.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1369() { RoundSpec s; s.gameId=131369; s.finalMult=5.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1370() { RoundSpec s; s.gameId=131370; s.finalMult=6.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1371() { RoundSpec s; s.gameId=131371; s.finalMult=6.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1372() { RoundSpec s; s.gameId=131372; s.finalMult=6.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1373() { RoundSpec s; s.gameId=131373; s.finalMult=6.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1374() { RoundSpec s; s.gameId=131374; s.finalMult=7.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1375() { RoundSpec s; s.gameId=131375; s.finalMult=7.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1376() { RoundSpec s; s.gameId=131376; s.finalMult=7.55; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1377() { RoundSpec s; s.gameId=131377; s.finalMult=7.80; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1378() { RoundSpec s; s.gameId=131378; s.finalMult=8.05; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1379() { RoundSpec s; s.gameId=131379; s.finalMult=8.30; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1380() { RoundSpec s; s.gameId=131380; s.finalMult=1.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1381() { RoundSpec s; s.gameId=131381; s.finalMult=1.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1382() { RoundSpec s; s.gameId=131382; s.finalMult=1.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1383() { RoundSpec s; s.gameId=131383; s.finalMult=1.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1384() { RoundSpec s; s.gameId=131384; s.finalMult=2.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1385() { RoundSpec s; s.gameId=131385; s.finalMult=2.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1386() { RoundSpec s; s.gameId=131386; s.finalMult=2.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1387() { RoundSpec s; s.gameId=131387; s.finalMult=2.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1388() { RoundSpec s; s.gameId=131388; s.finalMult=3.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1389() { RoundSpec s; s.gameId=131389; s.finalMult=3.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1390() { RoundSpec s; s.gameId=131390; s.finalMult=3.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1391() { RoundSpec s; s.gameId=131391; s.finalMult=3.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1392() { RoundSpec s; s.gameId=131392; s.finalMult=4.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1393() { RoundSpec s; s.gameId=131393; s.finalMult=4.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1394() { RoundSpec s; s.gameId=131394; s.finalMult=4.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1395() { RoundSpec s; s.gameId=131395; s.finalMult=4.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1396() { RoundSpec s; s.gameId=131396; s.finalMult=5.05; s.progressTicks=5; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1397() { RoundSpec s; s.gameId=131397; s.finalMult=5.30; s.progressTicks=6; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1398() { RoundSpec s; s.gameId=131398; s.finalMult=5.55; s.progressTicks=7; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1399() { RoundSpec s; s.gameId=131399; s.finalMult=5.80; s.progressTicks=8; return makeRound(s); }
inline std::vector<std::vector<std::uint8_t>> fixture_round_1400() { RoundSpec s; s.gameId=131400; s.finalMult=6.05; s.progressTicks=5; return makeRound(s); }
inline int countFixturesExt6() { return 200; }
}
